#!/usr/bin/env bash
set -eEuo pipefail

mapfile -t addresses < <(jq -rc '.[].data[] | .addressHorizenCompressed , .addressHorizenUncompressed, .claimDirectEhereumDerivedAddress, .claimDirectMultisigEthereumDerivedAddress' "${1:?Error - first argument needs to be a path to a json file generated by gen-test-addresses.js}")

amount="0.1"
batch_size="200"
from_address="zto4YEJgg4dvbkGebcDiY2E2EYrcB1Qj5ws"
network="-testnet"
#network=""
zen_cli="docker exec zen-testnet gosu user zen-cli ${network}"
#zen_cli="zen-cli ${network}"
object=""
objects=()
for i in "${!addresses[@]}"; do
  object+="{\"address\":\"${addresses[i]}\",\"amount\":${amount}},"
  if ! (( (( i + 1 )) % batch_size )); then
    object="${object::-1}"
    objects+=("${object}")
    object=""
  fi
done
if [ -n "${object}" ]; then
  object="${object::-1}"
  objects+=("${object}")
fi

for object in "${objects[@]}"; do
  opid="$($zen_cli z_sendmany "${from_address}" '['"${object}"']' 1 0.0001 true)"
  i=0
  while [ "$($zen_cli z_getoperationstatus '["'"${opid}"'"]' | jq -rc '.[].status')" != "success" ]; do
    if [ "$i" -gt 60 ]; then
      echo "timeout"
      exit 1
    fi
    i=$(( i + 1 ))
    sleep 0.5
  done
  sleep 1
  $zen_cli z_getoperationresult '["'"${opid}"'"]'
done
